# Generated by Django 6.1 on 2026-08-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='status',
        ),
    ]
